server:
  port: 8080
 
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/findbook?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity
 
#showSql
logging:
  file: my.log 
  level:
    com:
      example:
        mapper : debug
        service: debug